### ISSUE TITLE
PS3 ovladače

### ISSUE THREAD

**Issue by eldandee** [su-fit-vut/student-voice#11]
Slyšel jsem, že je v Kachně PS3, ale bez ovladačů. Co na to u vstupu dát kasičku a až by byly peníze tak by se ovladače dokoupily.

**Comment by Toaster192** [comment]
Ovladače jsou již objednány, kasička by proto mohla být na hry

**Comment by xbolva01** [comment]
alebo rovno na ps4 nech to aspoň trochu stojí za to

**Comment by Bordovsky** [comment]
Ovladače budou snad co nejdříve a snad se podaří uspořádat i nějaký turnaj ještě tento semestr.

Komentář o PS4 je trochu off-topic ale vyjadřím se k němu. PS3 byly zakoupeny fakultou za učelem vypočtů. Už několik let ale nejsou takto využívány a jen se na ně práší ve skladu. Proto jsem požádal fakultu o jejich zapujčení do klubu. Věřím, že někteří lidé ocení i starší hry.

Pokud @xbolva01 víš o nějakém PS4 které někde leží ladem a dalo by se darovat do studentského klubu, určitě mi napiš email.

Jelikož je dotaz otevirájící toto issue delší dobu zodpovězen, dovoluji si zavřít.
