### ISSUE TITLE
Automat na vodu

### ISSUE THREAD

**Issue by VeciCZ** [su-fit-vut/student-voice#13]
Na Facebookovou skupinu VUT FIT BIT 2017-2020 byla loni v červnu SU zveřejněna anketa ohledně automatu na filtrovanou vodu, který chtěla jistá firma poskytnout fakultě. Studenti o automat projevili jasný zájem (200 kladných hlasů a 2 záporné). Je stále v plánu do areálu FIT automat umístit?

**Comment by prodekanFITu** [comment]
Ja bych radsi automat na vodku.

**Comment by DekanFITu** [comment]
Já bych radši automat na formuláře s žádostí o ukončení studia.

**Comment by ivory0juvo** [comment]
Zmiňovaný automat na vodu (Filtermac) se prosadit nepovedlo: měsíční náklady na provoz byly vysoké.

Místo toho jsme zvolili jinou variantu: vybrali jsme jiný automat na vodu, který umí kromě perlivé/neperlivé (samozřejmě i filtrované) vody také vodu horkou. Tento automat řešíme s vedením fakulty a bude umístěn do budovy E (jak je automat na kávu).

Filtermac mezitím zvolil cestu jinou: zmiňovaný automat umístí do menzy (ale to už není v režii FITu, ale KAM). Tento automat by měl být umístěn na chodbu přd menzou (tzv. krček).

**Comment by ivory0juvo** [comment]
Jen pro zajímavost: Filtermac je umístěn na FASTu... byl jsem se tam minulé úterý podívat a co jsem stál v hlavní budově, kde je tento automat, vvyužilo jej asi během deseti minut 5 lidí, většinou zaměstnanců školy (soudím podle toho, že měli v ruce konve na vodu, ve kterých měli mátu a citron :) ).

**Comment by LowwinCZ** [comment]
Update: K realizaci automatu na vodu v budově E jsou všechny podklady předány, bohužel se stále čeká na realizaci. Tu musí dotáhnout správa areálu FITu, doufáme, že to bude brzy.

Co se týče automatu v menze, poslední informace které máme jsou, že KaM chtěl automat umístit přímo v menze, to se ale nelíbilo firmě, která jej měla dodat (Filtermac), ti ho chtěli mít na chodbě volně přístupný i mimo otevírací dobu menzy. Spolupráce s Filtermacem teda nevyšla ani tady a tento automat v areálu školy v blízké době nebude.

**Comment by kosciCZ** [comment]
Zdravím, jaký je status k tomuhle issue? Je tohle opravdu takový nesmírný problém?
Přikládám [link](https://www.facebook.com/FEKTVUT/photos/a.154087944687083/2412825792146609/?type=3&theater) na příspěvek o umístění brandovaného Filtrmacu na FEKT. Nebyla tady možnost sehnat sponzoring od nějaké z firem co s FITem spolupracují?

Plus mi přijde jako nesmysl umisťovat automat na vodu do menzy, která má otevřeno 11:00-14:30, kdežto studenti jsou na fakultě od rána do večera. Proč KAM nevznesl podobný požadavek i na FEKTu? (pokud to bylo v jeho režii. Pokud ne, tak jak je možné, že na FEKTu na to provozní náklady příliš velké nejsou?)

A konečně, nebylo by dobré zaurgovat správu areálu FITu? Od předání podkladů jsou to 4 měsíce a nechápu, kde to to může váznout.

**Comment by LowwinCZ** [comment]
Ahoj, ohledně Filtermacu, menze a podobných doporučuju si přečíst předešlé komentáře :)

Co se týče aktuálního řešení, dnes byla na fakultě zástupkyně firmy WaterLogic, která nám automat dodá. Tento automat bude umět vydávat chlazenou vodu, perlivou vodu a vodu o pokojové teplotě, voda bude procházet dvojí filtrací a UV zářením pro zajištění čistoty.
Automat bude umístěn v E vedle kávovaru (z důvodu přístupnosti vody).

Aktuálně tedy správa areálu čeká na nabídku firmy WaterLogic, konkrétní plán bude předložen tajemníkovi ke schválení, bude uzavřena smlouva a nainstalován automat.

Jsme tedy snad konečně v cílové rovince tohoto vleklého problému :)

**Comment by mbobcik** [comment]
Pohnulo se s tímto nějak? 🙂

**Comment by mbobcik** [comment]
Pohnulo se s tímto nějak? 🙂

**Comment by Darkvikis** [comment]
> Pohnulo se s tímto nějak? 🙂

Ano pohnulo. Fakulta dostala nabídku a rozhodla se pro pronájem automatu s případnou koupí po určité době. Proběhla jednání o ceně a smlouvě, ale ve chvíli, kdy firma WaterLogic poslala smlouvu, tak fakulta k ní měla připomínky, se kterými firma WaterLogic nesouhlasila, takže se teď řeší právní forma smlouvy mezi firmou a fakultou.
Snažíme se to co nejvíce urgovat, ale takové tahanice jsou docela složité.

**Comment by StoneboyCZ** [comment]
> Pohnulo se s tímto nějak? 🙂

Jen bych doplnil, že pokud se firma s fakultou nedohodne, začne hledání znovu. Automat se řešil na posledním kolegiu děkana a neměl jsem pocit, že by řešení bylo nějak blízko.

**Comment by Toaster192** [comment]
:fireworks: we did it mom
