### ISSUE TITLE
Anonymita

### ISSUE THREAD

**Issue by europ** [su-fit-vut/student-voice#14]
@su-fit-vut

> Repozitář pro anonymní sběr názorů na VUT FIT.

> ### Jak na to?
> Stačí přidat nový Issue nebo u aktuálních témat ohodnotit palcem nahoru/dolů jestli s nápadem/názorem souhlasíte.

Vaše *'Jak na to?'* **nie** je a ani nebude anonymné. GitHub zrejme nie je stavaný na tieto účely.

**Comment by Toaster192** [comment]
Platformu jsme volili na základě několika faktorů. Úplná anonymita ubírá možnosti diskuze (a mnohonásobně zvyšuje počet trollů apod.) a zároveň přímé propojení se školním loginem (například kdybychom uvažovali wis) samozřejmě způsobuje, že se poté člověk bojí k mnoha věcem vyjádřit.

A co se týče "střední cesty" tedy platforma, která vyžaduje registraci ale není nijak spojená se školou nám přišel github jako nejlepší možnost.

Omlouváme se tedy za zneužití slova "anonymní" a jsme otevřeni návrhům čím slovo nahradit.

**Comment by europ** [comment]
Zaujímavá voľba platformy.

Odporúčam vám slovo *'verejný'* keďže repozitár je typu public a je **dostupný úplne každému**.

**Comment by Sharp-Mike** [comment]
Já chápu, že v dnešní době je fakt těžké založit si fake account. Asi jsem někdo fakt zvláštní, když jich pár mám i právě z těchto důvodů. Silně pochybuji, že by jsi žádný neměl.
Založit mi to trvalo asi 2 minuty a mohu se naprosto volně vyjádřit k tématům, které bych možná veřejně nekomentoval, protože nevím, jaké by z toho mohli být vyvozeny důsledky.
Ano, mohou nějak dohledávat tvou IP, lokaci podle toho atd atd, ale buďme realisti, kdo bude hledat IP, lokace a původ lidí, kteří jen komentovali situaci na FITu a chtějí mít tady z toho lepší místo. 
Takže si myslím, že tvá poznámka je naprosto mimo, protože pro tento konkrétní účel, je GitHub opravdu anonymní.

**Comment by xbolva00** [comment]
No uz vidim ako vazne bude vedenie fakulty brat problemy vytvorene z fake/troll uctov..

**Comment by binczech** [comment]
Ach jo... Přesně tyhle projekty jen krásně ukazují, že fakulta se ubírá špatným směrem. Vyserte se na to a zkuste s vedením fakulty pouvažovat, jak vylepšit dotazníky, aby se studenti je nebáli vyplňovat, aby je vyplňovala většina studentů, aby výsledky z dotazníků měly nějakou sílu na změnu větších i menších problému na fakultě.

Když to takhle funguje na MUNI, proč by to nešlo i na tak prestižní fakultě, jakou je FIT. :P

**Comment by Sharp-Mike** [comment]
holka z MUNI se v jednom dotazníku vyjádřila a ze školy musela odejít, to je fakt řešení …

**Comment by DekanFITu** [comment]
Já bych navrhoval zrušit FIT.

**Comment by Budovi** [comment]
K tým dotazníkom si dovolím oponovať;
tento repozitoár / tracker nemá nič spoločné s dotazníkmi k predmetu. Naopak, problémy dotazníkov je jedna z vecí, ktorá by sa tu mohla riešiť.

Dotazníky sú zbieraním spätnej väzby FITu k predmetom.
Tento repozitoár je o zbieraní podnetov pre SU, aby sme vedeli, čo je treba riešiť s vedením.

**Comment by xbolva00** [comment]
Vacsina bodov z dokumentu z pred dvoch rokov je stale platna 
https://docs.google.com/document/d/1tS-YIP3nlfYE-_zGhbX5HUG_9cNIjycBOog1EjhwKl0/edit?fbclid=IwAR0LIKd4tpUJWe1blqoUcpQB2fYM-OnG6ydZQX-HbbAgY65Yk2WCLwlP5AI

Mozete zacat tam :)

**Comment by binczech** [comment]
> Tento repozitoár je o zbieraní podnetov pre SU, aby sme vedeli, čo je treba riešiť s vedením.

To znamená, že se už studenti bojí se svěřit i studentské unii, protože by je mohla naprášit vedení?

**Comment by Toaster192** [comment]
>repozitár je typu public a je dostupný úplne každému

Kdybychom zvolili čistě anonymní variantu tak by nebyla přístupná odkudkoliv? Nechápu čemu to vadí.

>No uz vidim ako vazne bude vedenie fakulty brat problemy vytvorene z fake/troll uctov..
 
Znovu nechápu jak by tomuto anonymita bez registrací pomohla. Proto také nejdou názory zde přímo fakultě ale přes SU kde se samozřemě nesmyslné návrhy profiltrují.

**Comment by xbolva00** [comment]
No filtrovanie navrhov clenmi SU je ale dost subjektivna vec.

"Co sa nam nepaci, to neposunieme dalej?"

**Comment by DekanFITu** [comment]
> Proto také nejdou názory zde přímo fakultě ale přes SU kde se samozřemě nesmyslné návrhy profiltrují.
Tak to byste si, studente, měli vyfiltrovat i tento celý repozitář, protože to je totální nesmysl.

**Comment by xbolva01** [comment]
Prečo by si niekto vytváral fake účet? :thinking:

**Comment by Budovi** [comment]
> > Tento repozitoár je o zbieraní podnetov pre SU, aby sme vedeli, čo je treba riešiť s vedením.
> 
> To znamená, že se už studenti bojí se svěřit i studentské unii, protože by je mohla naprášit vedení?

Nie, to znamená, že SU potrebovala nejaký efektívnejší spôsob ako zbierať spätnú väzbu a určovať jej priority. (Nečakane, jeden niekto niekde napísal nebolo dostačujúce.)

Ad. ostatní:

To, že máte možnosť vystupovať pod pseudonymom je podľa mňa vaša voľba / možná výhoda, nakoľko sa jedná o verejný priestor. Nerozumiem tomu, o čo vám ide.

**Comment by Toaster192** [comment]
@xbolva00 protože v popisu práce prostudentského týmu SU je filtrovat nápady za kterými stojí studenti :+1:

**Comment by xbolva02** [comment]
> Prečo by si niekto vytváral fake účet? 🤔
Protože to jde za pár sekund vytvořit přes temp mail? 🗡

**Comment by Toaster192** [comment]
Myslím že počet fake účtů ukazuje jak jednoduché to stále je být anonymní i zde, proč by to tedy nemohlo být na githubu kde alespoň ti co nemají potřebu trollit nemusi řešit registraci (předpokládám že na githubu bude velká část studentů)

**Comment by prodekanFITu** [comment]
já jdu dopiče stadyma

**Comment by DekanFITu** [comment]
> já jdu dopiče stadyma

Nope, půjdeš doprdele, až ti pošlu Rozhodnutí a zrušení pracovního poměru.

**Comment by cucorJedka** [comment]
Páči sa mi ako majú študenti konečne možnosť vyjadriť sa inak ako napísať osobne alebo hádzať papierik do krabičky, nemusia sa báť opýtať či vyjadriť, dostanú odpoveď čo najskôr to ide a predsa niektorí stále len hľadajú chyby a nie riešenia...

**Comment by Toaster193** [comment]
Myslím že počet fake účtů ukazuje jak jednoduché to stále je být anonymní i zde, proč by to tedy nemohlo být na githubu kde alespoň ti co nemají potřebu trollit nemusi řešit registraci (předpokládám že na githubu bude velká část studentů)
 
Ano milý kolego je to velmi jednoduché.😉

**Comment by xbolva01** [comment]
> já jdu dopiče stadyma

Tak snáď sa budeme vyjadrovať slušne!

**Comment by binczech** [comment]
> > já jdu dopiče stadyma
> 
> Tak snáď sa budeme vyjadrovať slušne!

[http://milujipraci.cz/#08](URL) [http://milujipraci.cz/#01
](URL) SU cenzuruje [http://milujipraci.cz/#00
](NEDÁME SE)

**Comment by Toaster192** [comment]
https://github.com/su-fit-vut/student-voice/commit/2080598c1d167467ea1aeea564c3924616819510

Na problémy v README klidně pošlete pull request (ten se dá také komentovat).

Pokud nemáte jiné konstruktivní námitky tak navrhuji uzavřít issue.

**Comment by michkot** [comment]
Musím říct, že až teď jsme si někteří všimli, že Toaster192 != Toaster193 ... jakože, trolli jsem čekal, ale že ještě bude někdo dělat trollo-identity-theft mě nenapadlo.
