### ISSUE TITLE
Priestory pre studium

### ISSUE THREAD

**Issue by TheKuko** [su-fit-vut/student-voice#18]
Chybaju mi nejake normalne (a hlavne pohodlne) priestory na [samo]studium/travenie casu na fakulte. Pribudli vaky v kniznici, ale stale to nie je nejak ono... 

Inspiroval by som sa kniznicou na [UEF](https://blogs.uef.fi/ueflibrary/tag/remontit/) -- tie cervene sedacky pri oknach (posledna fotka) su luxusne, ked je clovek unaveny moze si aj opriet hlavu a podriemat, moze tam pohodlne presediet cely den a su tam aj zasuvky. Su tam aj makke lavice (8. fotka) pre riesenie veci v skupinach, takisto so zasuvkami...alebo tie vaky na predoslej fotke.

[FIIT STU](https://www.facebook.com/FIIT.STU/posts/2345877998777912?__tn__=-R) priestory tiez nevyzeraju zle.

V kniznici moc na to nie je miesto, ale rozne po fakulte by sa naslo (chodba vedla kniznice; pod mostikom medzi budovami, atd.)

**Comment by Bordovsky** [comment]
Prostory na obou odkazech jsou opravdu hezké a zajímavé. V podmínkách naší fakulty je ale několik problému, které limitují možnosti dalšího vybavení. 

Prvním je ten, že fakulta je architektonickým dílem a nelze zde umístit vybavení, které by narušilo současný design.Vaky a tabule jsou věci ktere v připadě potřeby mužeme snadno přemistit, ale s gauči by to bylo horši.

Relativně zřejmým problémem je samotné vybavení nehlídaných prostor. Fakulta má obavy, že by vybavení jako pytle nebo gauče na chodbách bez přímého dozoru došly k újmě. I současné tabule jsou využívány některými studenty jako koloběžky a pravděpodobně nebudou na chodbách dlouho.

**Comment by Toaster192** [comment]
@TheKuko Pokud náhodou máš nějaký nápad jak zlepšit prostory tak, aby vylepšení splňovalo podmínky fakulty, potom moc rádi pomůžeme ale obávám se že spousta nápadů tímto neprochází.

Dokud se nic nenajde, uzavírám issue
