### ISSUE TITLE
[MIT] Rušení MATu?

### ISSUE THREAD

**Issue by Redak37** [su-fit-vut/student-voice#2]
Zaslechl jsem, že se bude rušit povinný předmět z magisterského studia - MAT, co je na tom pravdy? bude nějaká náhrada?

**Comment by Toaster192** [comment]
Ohledne tohoto byl rozeslan mail dekanem kde snad zodpovedel vse (uzaviram issue)

**Comment by Redak37** [comment]
Pokus o komentář
