### ISSUE TITLE
Zverejnenie zaznamov

### ISSUE THREAD

**Issue by 0xFUCK** [su-fit-vut/student-voice#21]
Je 7. týždeň semestra a záznamy stále nikde. Môže SU upozorniť pani Skokanovú, že by sa už konečne mala venovať strihaniu záznamov?

**Comment by StoneboyCZ** [comment]
Mají předměty, o které máte zájem, povolené záznamy? Letošní přednášky IZG už na video serveru vidím...

**Comment by 0xFUCK** [comment]
Áno majú. Je zaujímavé, že iba IZG je na videoserveri.

**Comment by StoneboyCZ** [comment]
Je možné, že jsou ještě nějaké problémy s technikou. V každém případě, dotazy zpracování záznamů neurychlí :(.

**Comment by LowwinCZ** [comment]
Dotazů na záznamy jsme letos už položili tolik, že nás musí mít vedení plné zuby, bohužel naše dotazy ani připomínání se nevedou moc daleko. Naposledy jsme se na záznamy ptali před čtrnácti dny, kdy nám paní Skokanová odepsala, že odpověď ohledně záznamů najdou všichni studenti po přihlášení na videoserveru. Pokud ji tam najdete vy, budeme rádi, my už ji dnes nenašli :) (Legendy říkají, že ona tajná zpráva slibovala postupné zveřejňování záznamů v týdnu od 11. 3.)

**Comment by michkot** [comment]
Dupla, viz #1 a poslední odpověď zde.
