### ISSUE TITLE
Predĺžiť skúškové

### ISSUE THREAD

**Issue by 0xFUCK** [su-fit-vut/student-voice#23]
Budúcu zimu sa bude skúšať aj cez prvý týždeň letného semestra.

Nie je to už choré? FIT sa tvári, že mu záleží na študentoch, no robí opak a vytvára zbytočne fyzické a psychické tlaky či už počas semestra a teraz aj sťažuje skúškové.

Prečo sa SU a Akademický senát nevenuje tejto otázke?

Skúškové za zimu a leto je potrebné predĺžiť aspoň o týždeň.

**Comment by StoneboyCZ** [comment]
Netypická situace příští zimu je dána pevně daným plánem akademického roku, za který je zodpovědný rektorát. Žádná jiná fakulta s ním nemá problém, proto není vůle ho změnit. 

Změny ve zkouškovém období ale asi nemá příliš smysl řešit v rámci fakulty :(, je nutné protlačit změnu na celém VUT.

**Comment by 0xFUCK** [comment]
> Žádná jiná fakulta s ním nemá problém, proto není vůle ho změnit.

Značný počet fakúlt ma variantné térmíny skúšok, prípadne obtiažnosť skúšky (oproti FIT) je výsmech

**Comment by StoneboyCZ** [comment]
@0xFUCK To může být pravda, ale na situaci příští rok to nic nemění.

**Comment by 0xFUCK** [comment]
> @0xFUCK To může být pravda, ale na situaci příští rok to nic nemění.

Nenarážal som iba na budúcu zimu, ale na skúškové na FIT do budúcich rokov... ITAI prinesie nové predmety -> skúšky+++++

**Comment by StoneboyCZ** [comment]
Jak jsem psal, prodloužení zkouškového je nutné řešit na úrovni VUT. Z pohledu plánování zkoušek bude příští rok obtížný (jak vzhledem k novým studijním programům, tak vzhledem ke kratšímu zkouškovému v zimě), ale naplánovat půjde.

**Comment by StoneboyCZ** [comment]
A asi by měla zaznít ještě jedna věc: situaci jsme se už několikrát věnovali na kolegiu děkana, hledali jsme řešení se SÚ a se studenty ve SKASu . Možné zkoušení v prvním týdnu semestru se ukázalo jako nejlepší řešení.

**Comment by 0xFUCK** [comment]
Takže ďalší problém sa vyriešil. Super.
