### ISSUE TITLE
Riešiť najskôr problémy študentov okolo štúdia, až potom zábavky

### ISSUE THREAD

**Issue by 0xFUCK** [su-fit-vut/student-voice#25]
Mám pocit, že SU prioritne rieši iba zábavky, hry, deskovky, a iné zábavné akcie a na večné a často náročné problémy týkajúce sa FITu strká hlavu do piesku.

Je mi jasné, že dostanem veľa palcov dole, práve od týchto ľudí, ktorý chodia na tieto akcie a často sú to Ečkári a ľudia 2. opravných termínov.

**Comment by Bordovsky** [comment]
Tohle je dost zajímavé issue. Nevím, z které strany začít formulovat odpověď. Začneme od konce.

> ...na večné a často náročné problémy týkajúce sa FITu strká hlavu do piesku.

Věcné a náročné problémy týkající se FIT jsou věc, která nejde vyřešit přes noc. Unie řeší s vedením fakulty spoustu věcí. Vedeni fakulty ale neplní to, co si Unie pískne, jsou svázaní zákony, vyhláškami, rektorátem i ostatními fakultami. Nebudu zde otevírat konkrétní příklady, protože ty si zasluhují vlastní vlákna. Prakticky nemáme ani na fakultu nějaké "páky", jak ji přimět něco dělat. Spousta nápadů končí smetena ze stolu ne snad proto, že by vedení nemělo zájem nám vyjít vstříc, ale protože je natolik svázána, že realizace není v její moci. I přesto si myslím, že se fakulta za poslední roky změnila a je pro studenty přívětivější.

Pokud se ti zdá, že SU by něco řešit měla a neřeší, máš možnost to napravit. Jak? 

**Můžeš nás informovat, že nějaký problém vůbec je.** 
Unie má omezené kapacity, je nás jen nějaké procento z celkového počtů studentů na FIT, takže nemůžeme postřehnout každý problém. Informovat nás šlo vždy emailem, na facebooku a nově zde na GitHubu. Taktéž je možné si s námi domluvit osobní schůzku nebo přijít na zasedání a vznést své připomínky osobně.
(*Přijde mi úsměvné až směšné, že se tato poznámka objevila asi týden po otevření této platformy pro sběr podnětů od studentů.*)

> Mám pocit, že SU prioritne rieši iba zábavky, hry, deskovky, a iné zábavné akcie a ...

Zde asi došlo k nepochopení, čím Unie je, respektive kým je tvořena. Všichni z nás jsou studenti z FIT, mnoho pracujících a se sociálním životem. V teorii člen Unie věnuje volný čas, který mu zbude k tomu, aby se studenti na fakultě měli lépe. (V praxi se členově věnují SU na úkor svých známek, pracovního času = peněz a možností socializovat se mimo FIT). Členové nejsou volení, může se jím stát kdokoli. Nejsme za naši práci placeni a ani nijak kompenzování například úlevami na zkouškách/projektech. Tim pádem nemáme ani žádné "páky" na členy, aby dělali vyloženě to, co je "večné" a náročné. 

Členové dělají, co chtějí. Spousta z nás považuje věci, které řeší, za věcné, potřebné a prospěšné studentům a mohou se cítit tvým komentářem uraženi. (Pokud k tomu ovšem přistoupíme pozitivně, je potřeba více dát najevo, co děláme, i když to je vidět na každém zasedání SU, které je pro studenty FIT přístupné).
Pokud si skupina členů myslí, že lidem na FIT pomůže možnost vytvořit si mezi sebou vazby napříč ročníky například u deskovek, proč jim k tomu neposkytnout zázemí? Pokud někdo přijde do Unie s tím, že by studentům prospělo mít na chodbách tabule a víc seminárek proč mu neposkytnout podporu?
Máme členy, kteří se věnují dotazům studentů – sbírají je, předávají je fakultě a odpověď zpět předávají studentům. Pokud se jedná o dostatečně častý dotaz nebo je jich příliš mnoho, jsme schopni a ochotni zprostředkovat setkání studentů s vedením fakulty jako v minulosti. Některé dotazy je zbytečné směřovat na vedení, protože víme, že stále není možnost, jak studentům vyhovět. Jiné vytahujeme stále dokola.

Pokud máš pocit, že by unie měla dělat něco jiného, nic ti nebrání si podat přihlášku a začít daný problém řešit osobně. (Nebo SU obejít a řešit přímo s fakultou, je vysoká pravděpodobnost, že budeš odkázán na to, že daný problém jsme už projednávali, ale přeju ti upřímně mnoho štěstí, pokud se rozhodneš jít touto cestou.)

**Comment by michkot** [comment]
Tady Gabriel to myslím popsal hezky... 👍 

Protože mě tvůj komentář trochu triggruje, tak odpovím taky, poněkud příměji. Bohužel mnoho lidí z FITu neví co a proč je Studentská unie (nutno dodat, to se vždy mění podle lidí, kteří ji tvoří) a upřímně, je to náš trvalý problém a mě osobně to dost _sejří_. Věnujeme se všemu možnému. V některých případech to jde snadněji protože si to prostě uděláme sami, někde můžeme (jen) vyjednávat a dodávat pohled na věc. Dovolím si odhadnout, že tvé 

> večné a často náročné problémy týkajúce sa FITu

typicky budou spadat do té druhé kategorie.

Pokud jsi stále naivní (bez negativních konotací) a myslíš si, že něco z těchto věcí můžeš ovlivnit (jen a pouze) vlastníma rukama, mohl bys např. zkusit kandidovat studentské komory akademického senát, a tam snad z pozice (teoretické) síly měnit postoje a priority fakulty. Osobně považuji tohle za slepou cestu.

Pokud se smíříš s tím, že některé změny můžeš iniciovat nebo je třeba jen okomentovat, ale už se jich jako student nemusíš dožít, tak si pochopil alfu a omegu "náročných problémů FITu". 
_Jo a jinak, zcela upřímně, dost "náročných problémů" má celé vysoké školství v Čechách, takže doporučuji neztrácet víru v politiku a ministerstvo školství._

**Comment by michkot** [comment]
Jinak, i podle toho co jsem napsal: ten "pocit", že tvoříme spíš zábavní studentský program, než že by jsme někde veřejně debatovali o problémech fakulty či tak něco, je defacto očekávávatelný. 

A na tom "pocitu"... toho asi nepůjde moc změnit. Namátkou, protože se úplně nevyžíváme v psaní reportů o reportech; některá jednání, kterých se lidé v SU účastní, pracují s "pracovními verzemi", které by neměli opouštět jednací skupiny; někdy zjistíme, že to či ono už někdo zkoušel realizovat před námi, vyslechneme si shrnutí argumentů, proč by to nefungovalo z právních nebo jiných důvodů a po zamyšlení uznáme, že by to fakt nešlo.

Na druhou stranu, v SU jsou lidi (i když rozhodně ne 100%) kteří se o problematiku upřímně zajímají, dávají konstruktivní feedback a dohromady tvoří takovou živou paměť toho, co se už zkoušelo a co ještě ne. To je IMHO ta myšlenka, jak něčeho rozumně efektivně dosáhnout.

Takže, určitě bych neříkal, že před něčím strkáme hlavu do písku.

**Comment by 0xFUCK** [comment]
Solved.
