### ISSUE TITLE
Uvádzanie študijného oboru na písomkách

### ISSUE THREAD

**Issue by venteda** [su-fit-vut/student-voice#28]
V WAP a PDS sa u polsemky muselo uvadzat meno oboru. Co to ma znamenat??
Pisomky sa azda upravuju podla toho kto je z akeho oboru? Alebo sa robia korekcie? 

Moze SU zistit co je tymto poziadavkom, aby sa uvadzal obor?

**Comment by LowwinCZ** [comment]
Můžeme se zeptat, ale já třeba obor nevyplnila a nikdo se neozval, že by s tím měl problém :)

**Comment by LowwinCZ** [comment]
Zde vyjádření docenta Ryšavého:
"Hezký den,

uvedení oboru slouží pouze pro vytvoření statistiky, jak si v předmětu vedou studenti různých oborů. V žádném případě nemůže uvedení či neuvedení oboru ovlivnit výsledek půlsemestrální zkoušky. 

S pozdravem, 

Ondřej Ryšavý"

Pan profesor Hruška odpověděl, že se zeptá přednášejících, kteří test zařizují, a odepíše až bude vědět.

**Comment by LowwinCZ** [comment]
Zasílám odpověď  p. Polčáka, respektive pana Hrušky:

Hezký den,

uvedení oboru slouží pouze pro vytvoření statistiky, jak si v předmětu vedou
studenti různých oborů. V žádném případě uvedení či neuvedení
oboru neovlivňuje výsledek půlsemestrální zkoušky.

A ještě poznámku:

Studijní obor je uveden ve studijní dokumentaci k předmětu a tudíž nejde o novou informaci pro vyučujícího.

Tudíž všichni vyučující mají informaci o studijních oborech studentů ve svých předmětech.
Máte-li nějaký důkaz o zneužití, obraťte se na příslušného proděkana.

S pozdravem Hruška
