### ISSUE TITLE
Jak to bude s kachničkou?

### ISSUE THREAD

**Issue by Redak37** [su-fit-vut/student-voice#3]
Jak to bude tento semestr, je nějaký plán, od kdy bude zase normálně fungovat bar a tak podobně?

**Comment by Toaster192** [comment]
Potřebujeme zlepšit evidenci pohybu věcí na baru

proto pracujeme na novem systemu ktery potrebujeme prvne dodelat

viz. :

> Jsi frontend vývojář? Otravuje tě, že Kachna je otevřeva v provizorním režimu a chceš pomoct?
> 
> Hledáme pomoc s implementací webové aplikace pro informační systém postavený na REST API (zdokumentovaném pomocí OpenAPI 3). Pivní odměna jistá (případně dle domluvy v rámci možností). V případě zájmu nás neváhej kontaktovat (xbudis02@stud.fit.vutbr.cz nebo prostřednictvím Discordu SU).

Jde na poměry SU o velký projekt, který byl dlouho odkládán, a proto jsme se do toho rozhodli "hodit vidle" aby se konečně realizoval.

**Comment by StoneboyCZ** [comment]
Ano, je vhodné upozornit doktora Smrčku, že musí záznam zveřejnit co nejdříve, jakmile bude připraven. Na přípravu záznamu ale doktor Smrčka nemá žádný vliv a nemá ani jak ovlivnit délku přípravy. To nemohou ani studenti.

**Comment by 0xFUCK** [comment]
No môžete ako súkromné osoby nakúpiť alkohol a potom ho študentom v kachne predávať, to vám ako súkromnej osobe nik nezakazuje, nie?

**Comment by LowwinCZ** [comment]
Jako soukromá osoba si teď můžeš do Kachny donést své pití sám, to ti taky nikdo nezakazuje :)

**Comment by Toaster192** [comment]
Včera proběhla znovu klasická otvíračka se vším všudy a vše je tedy při starém (nebo ještě lepší díky kachnakartám a podobně)! 

Uzavírám issue
