### ISSUE TITLE
Integracia fitusky do discordu

### ISSUE THREAD

**Issue by tomaskender** [su-fit-vut/student-voice#31]
Myslim, ze nepoviem nic nove, ked spomeniem, ze pred kazdou pisomkou sa objavia na discorde materialy na opakovanie. Na fituske sa vsak objavi iba zlomok tohto obsahu, kedze je zbytocne pracne prihlasovat sa na fitusku a davat to tam. Budme k sebe uprimni, sme itckari a sme lenivi. :) Z tohto dovodu by bolo fajn prepojit fitusku a discord napriklad prostrednictvom bota, ktory by sa na discorde dal tagnut v tele spravy a danym contentom a tento bot by to nasledne podla roomky predmetu (a nejakych parametrov) nahral na fitusku do vhodnej kategorie a threadu. Tento pristup by sa dal aplikovat aj na dolezite informacie z discordu, ktore sa na discorde stratia v spame (a nie, pinovanie sprav v channeloch nestaci). Myslim teraz napriklad na recenzie predmetov apod., ktore by sa tu dali pekne, prehladne zadelit do kategorii a kazdy by si tu nasiel, co ho zaujima.

**Comment by TheGreatfpmK** [comment]
Mne príde že pinnovanie na dc je viac ako dostatočné aj tak sa písomky z minulých rokov riešia iba pred písomkou a mať bota na to aby si ho niekto každú hodinu volal lebo chce zobraziť písomku z minulého roka mi neznie ako najlepšie riešenie... Možno by sa tak dalo pár vecí prepojiť lepšie ale nepríde mi to moc potrebné

**Comment by CtrlZmaster** [comment]
Ako správca Fitušky ti môžem aktuálne povedať len: "Dobrý nápad, ale momentálne to nepôjde." 

Existuje len málo študentov, ktorí vôbec majú záujem spravovať Fitušku. Na posledný náborový príspevok pre adminov som dostal JEDNU odpoveď a to tiež od študenta, ktorý už prejavil záujem predtým. Vystihol si to skvele s vetou: "sme itckari a sme lenivi". 

Momentálne beží Fituška na phpBB a v príprave je nová, ktorá bola napísaná ako diplomová práca v Jave. Mám čo robiť (a aktuálne nerobím nič okrem projektov a polsemestrálok) už len s tým, aby sme možno niekedy v dohľadnej dobe zvládli nasadiť vôbec túto novú Fitušku, ktorá pôvodne mala byť prepojená s Facebook skupinami - čo je v podstate Discord bot v bledomodrom, ale ten nápad vznikol skôr, než bol Discord spopularizovaný. A to pravdepodobne tiež nepôjde po škandále s Cambridge Analytica, keďže Facebook začal sprísňovať všetky pravidlá a nové aplikácie (nejako to na FB pristupovať musí) musia byť schválené priamo Facebookom.

V súčasnej situácii je s Fituškou práce až-až (myslím, že je správny čas spomenúť, že ani hosting a ani doménu nemáme osobne pod kontrolou), takže pokiaľ tím administrátorov nebude väčší, myslím, že udržanie aktuálnej Fitušky v chode je dostatočne dobré.

**Comment by tomaskender** [comment]
@TheGreatfpmK bot by sluzil iba na upload, kedze tam to viazne najviac.
@CtrlZmaster pisal som sz na fituske

**Comment by TheGreatfpmK** [comment]
@tomaskender Aha tak som to zle pochopil... V tom prípade by to bolo určite nice ale tak asi nič v dohľadnej dobe

**Comment by Toaster192** [comment]
Chápu tedy správně že nápad by byl se současným stavem fitušky téměř nerealizovatelný? (Jestli můžu uzavřít issue)

**Comment by tomaskender** [comment]
Zo strany fitusky by neboli potrebne ziadne upravy (resp. ak hej, tak minimalne), ale nema to uz zmysel riesit, kedze je vo vyvoji nova verzia fitusky, ktora nahradi tu staru. Pokial sa teda bude robit bot, tak uz pre novu fitusku. /close
