### ISSUE TITLE
Přidání odkazů na privátní stránky předmětů do WISu

### ISSUE THREAD

**Issue by EveryManAKing** [su-fit-vut/student-voice#37]
Název je myslím všeshrnující.
Nebylo by možné prosadit, aby na stránce předmětu ve WISu nebyl kromě odkazu na web a u některých na wiki i odkaz přímo na privátní stránky (pokud je samozřejmě má) místo toho, aby byly schované na webu?
Já vím, jen věc pár kliknutí kvůli kterým se svět nezboří, ale současný stav je prostě otravný a neintuitivní.

**Comment by LowwinCZ** [comment]
Požádali jsme pana inženýra Lampu o přidání a odkazy už můžete nálézt we WISu :)
Upozorňuji, že pro učitele je pole pro privátní stránky text field, kam můžou napsat cokoliv, takže pokud se vám u některého předmětu nebude líbit co se vám zobrazuje, řešte to, prosím, s konkrétními vyučujícími.

**Comment by Toaster192** [comment]
Vyřešeno, uzavírám

**Comment by CtrlZmaster** [comment]
Na rozdiel od iných nedávnych zmien vo WISe, táto bola naozaj pozítivna, ale ocenil by som, keby bola lepšie prevedená. Odkaz na vrchu "Web stránky" by som premenoval na "Karta předmětu". Ďalej by som tomu dumpu odkazov na web stránky dal aspoň ten novouvoľnený nadpis Web stránky, nech tam tie odkazy tak nevytŕčajú ako teraz.

**Comment by StupydHors** [comment]
Každý deadline by mohl mít studentem odškrtnutelnou kolonku "splněno".
Po přihlášení by se na pravé straně WISu mohla zobrazit tabulka nadcházejích termínu které ještě nejsou "splněny" ať už tedy registrace na semestrálku/cvičení nebo deadline projektu.
