### ISSUE TITLE
Fuchs a používanie WISu

### ISSUE THREAD

**Issue by FairyRegedix** [su-fit-vut/student-voice#38]
Veľa študentov si sťažuje, že nevedia používať _VUT portál_, ktorý je primárnym prostriedkom informácií v predmete **IMA1**. Ako prváci sme boli naučený pracovať s _WISom_ a veľa ľudí sa celkom stráca v inom informačnom systéme. Hlavne im prekáža, že zvolený informačný systém bol vybraný štýlom " lebo som sa rozhodol " alebo " mne sa v ňom pracuje lepšie ". 

Tým, že vyučujúci budú pridávať materiály do portálu, v ktorom nevedia všetci pracovať alebo si ich vyhľadať môže mať za následok zhoršenie študijných výsledkov.

**Comment by StoneboyCZ** [comment]
Krásné ráno. Pokoušel jsem se přesvědčit o používání WISu doktora Fuchse. Bohužel mi jako odpověď zaslal následující:

"Vzhledem k tomu, že pro vyučující z FEKTu je výrazně jednodušší vést
veškerou studijní agendu v IS VUT, bude tomu tak i v předmětu IMA1. "

Budeme se snažit o zlepšení v příštích letech.

**Comment by FairyRegedix** [comment]
Aj Vám krásne ráno. Ja osobne nemám problém s používaním IS VUT, ale zaujíma nás postoj študentov na túto tématiku, keďže sa stále objavujú dotazy, kde si študenti môžu pozrieť výsledky písomiek alebo nájsť materiály k učeniu. Aj tak si cením Váš postoj k takejto maličkosti.

**Comment by StoneboyCZ** [comment]
Pokud vím, postoj vedení FIT je takový, že bychom rádi viděli materiály a termíny pro všechny povinné předměty minimálně v prvním ročníku bakaláře ve WISu.

**Comment by Toaster192** [comment]
Uzaviram protoze WIS uz nebude :cry:
