### ISSUE TITLE
Nepoužívat certifikáty podepsané nedůvěryhodnou CA

### ISSUE THREAD

**Issue by kudlav** [su-fit-vut/student-voice#39]
V současné situaci jsou některé servery, ke kterým přistupují uživatelé, zabezpečeny certifikáty, které podepsala [certifikační autorita VUT](http://ca.vutbr.cz/). Je to řešení pro uživatele pracnější a méně bezpečné.

Je nutné na všechna zařízení stáhnout a nainstalovat kořenovou certifikační autoritu. CA se stahuje z nezabezpečených stránek ca.vutbr.cz. Stažená certifikační autorita tedy může být podvržená a nainstalování představuje riziko.

Servery s CA VUTBR:
- ~~wis.fit.vutbr.cz~~
- smtp.stud.fit.vutbr.cz
- ~~video1.fit.vutbr.cz~~
- ~~www.stud.fit.vutbr.cz~~

Servery s Let's Encrypt:
- email.fit.vutbr.cz
- roundcube.fit.vutbr.cz
- cas.fit.vutbr.cz
- www.fit.vut.cz

Pokud by škola přešla například na Let's Encrypt, bylo by to více user friendly a navíc by to přineslo zvýšení zabezpečení.

Ne všude je možné CA nainstalovat, gmail.com již neumožňuje používat smtp servery školy.
![obrazek](https://user-images.githubusercontent.com/11516259/81484941-0a85d680-924a-11ea-8b7e-56fa774beb9f.png)

**Comment by kudlav** [comment]
Nechť můj názor není jediný:
![obrazek](https://user-images.githubusercontent.com/11516259/81485120-11611900-924b-11ea-83f4-84d4e2278d81.png)
![obrazek](https://user-images.githubusercontent.com/11516259/81485128-22aa2580-924b-11ea-9f3d-16b97fb70bc0.png)

**Comment by CtrlZmaster** [comment]
Prihadzujem do diskusie ešte aj CA CESNETu, ktorá je predvolene dôveryhodná v prehliadačoch: https://pki.cesnet.cz/cs/st-cca-services.html

**Comment by Budovi** [comment]
> TLS negotiation failed, the certificate doesn't match the host

Čo to spraví keď zmeníš server priamo na `eva.fit.vutbr.cz`? :sweat_smile: Som lenivý zisťovať aký certifikát to vráti a teda či je to chyba konfigurácie alebo tomu vadí nedôveryhodný certifikát a len vypisuje zlú hlášku...

**Comment by kudlav** [comment]
> Čo to spraví keď zmeníš server priamo na `eva.fit.vutbr.cz`? 😅 Som lenivý zisťovať aký certifikát to vráti a teda či je to chyba konfigurácie alebo tomu vadí nedôveryhodný certifikát a len vypisuje zlú hlášku...

To stejné...

**Comment by Budovi** [comment]
Neobhajujem súčasný stav, len som chcel overiť či by nefungoval rýchly workaround pre aktuálny problém. ca.vutbr.cz je výsmech.

**Comment by michkot** [comment]
_Pro případný workaround pro gmail SMTP můžeme založit separátní issue (nehledě na to, že předání přihlašovacích údajů do IS FIT googlu bylo i ze strany zaměstnanců CVT označeno za porušení studijních regulací)._ 

Ale souhlasím, že pro fakultu IT je to poněkud bizardní situace a opravdu nikomu nesežeru, že je bezpečnější mít pro client-oriented služby certifikát podepsaný vlastní speciální certifikační autoritou, abych mohl klient kontrolovat, že protistrana se opravdu ověřuje certifikátem konkrétního původu. Hlavní důvody:
 - dostupnost kořenového certifikátu (půjdu s fleškou na CVIS VUT nebo CVT FIT VUT? ne, stáhnout z HTTP!)
 - nemožnost přidat důvěryhodný kořenový certifikát ve velkém množství software používaných koncovými uživateli (nejsme enterprise, abychom se snad omezovali na pár produktů které tuto funkcionalitu umožňují)
 - nedůvěra nových uživatelů fakultních služeb v se stránku kterou jim prohlížeč označí jako nebezpečnou, mnoho uživatelů si CA certifikát do prohlížeče/systému vůbec nenainstaluje a jen schválí permanentní výjimku bez bližšího zkoumání.
Podtrženo sečteno, pokud by mi někdo tvrdil že současný přístup je bezpečnější pro komunikaci než let's encrypt, tak je to jako tvrdit že "máme vynucená 100+ znaků dlouhá přihlašovací hesla která se skládají z max 50 alfanumerických znaků"... uživatel se z počítače raději nikdy neodhlásí :D

**Comment by ZdenekM** [comment]
Jsou v této věci nějaké novinky? Řeší se to někde s někým aktivně?

**Comment by Toaster192** [comment]
@ZdenekM @kudlav Dostal jsem od Ing. Lampy pekne vysvetleni ale od te doby (20.5.) mi neodepsal ani na jeden ze 2 emailu kde jsem se ptal, jestli souhlasi se zverejnenim emailu.

**Comment by Budovi** [comment]
Pokúsim sa zhrnúť mne momentálne známe stanovisko:

- pre SMTP používa fakulta (údajne rozšírený) štandard [DANE](https://tools.ietf.org/html/rfc7672) a nerozumie, prečo sa Google rozhodol tento spôsob ignorovať a súčasne neumožniť špecifikovať užívateľský certifikát,
- na mnohých verejných službách sa prešlo na Let's encrypt, a je v pláne v tomto trende pokračovať v budúcnosti,
- na niektorých službách je toto však problém realizovať (ako príklad je práve SMTP kvôli aktualizácii zodpovedajúcich záznamov TLSA v DNS).

Ďalšie poznámky:

- p. Ing. Lampa si nemyslí, že je rozumné dávať svoje heslo v textovej podobe tretej strane,
- korporátne CA sú vo svete normálne a rozšírené,
- CVIS na VUT pracuje s certifikátmi nevhodným spôsobom.

--------
Čo mne osobne ešte príde problematické je spôsob, akým je šírený samotný verejný kľúč CA VUT. Na to by sme sa teoreticky mohli ešte spýtať, ale svojím spôsobom to nerieši moc problémov. A tiež možno zatiačiť na CVIS na úrovni VUT? Nie som si istý.

**Comment by SuperMartas** [comment]
Jen poznámka s předáváním hesla třetí straně:
Dle mého názoru je to vlastně v podstatě stejné, jako kdybych heslo zadal do klienta Thunderbirdu nebo i webového emailu poskytovaného přímo školou (Roundcube?) prostřednictvím webového prohlížeče. Po cestě existuje spousta prvků, které mohou heslo případně vzít a odeslat někomu dalšímu - ať už jde o webový prohlížeč, klient Thunderbird, operační systém nebo třeba samotný hardware v klávesnici či jeho ovladač. Spíš bych tedy řekl, že je to na bázi důvěry a alespoň pro mě jsou Google, resp. GMail a Chrome dostatečně důvěryhodní.

Co se týče porušení studijních regulací, tak jediné, co jsem našel, je článek 2, odstavec 5 dokumentu https://www.fit.vut.cz/units/cvt/net/Smernice-22-2017.pdf:
> Uživatel nesmí poskytnout přidělené jméno a heslo jine osobě.

Pokud za osobu budeme považovat i Google, tak v tom případě by nebylo možné, jak už jsem naznačil v předchozích odstavcích, zadávat přihlašovací údaje do wisu, Roundcube a tak dále ani skrze webový prohlížeč, operační systém apod. V takovém případě by heslo muselo zůstat jenom v hlavě, což dle mého názoru nebylo účelem této "regulace".

Budu rád za případné vyjasnění, pokud se v některém bodě pletu.

**Comment by Redak37** [comment]
Podle mě sis tak trochu sám odpověděl, když jsi řekl, že roundcube je poskytovaný přímo školou, nelze tak mluvit o poskytování údajů třetí osobě. Třetí osoba je kdokoliv, kdo nejsi ty, nebo ona škola.

Thunderbird funguje jako lokální poštovní klient, který si lokálně uloží přihlašovací údaje, není tak prakticky ani moc rozdíl v používání thunderbirdu od používání webového prohlížeče, údaje se (alespoň na vědomé úrovni, tzn. pokud nedochází k odcizení dat) neposílají třetí straně, která si to někde u sebe nespecifikovaně jak uloží.

To že se přihlašovací údaje dají třetí stranou potenciálně ukrást nemůžeš používat jako argumentaci pro dobrovolné odevzdání údajů třetí straně.

Ad. "považování Googlu za osobu"... společnost Google je ve smyslu zákona tzv. "právnická osoba", takže ano, vztahuje se to i na něj.

**Comment by SuperMartas** [comment]
Jaký je rozdíl v tom, jestli jsou data uložena na mém PC (v případě Thunderbirdu) nebo na vzdáleném PC někoho jiného (servery GMailu, Thunderbird na vzdáleném PC)? V případě, že si od někoho budu např. pronajímat jeho PC, k němu se vzdáleně připojovat (nebo ho mít pronajatý i pouze doma, kde mi ho může, stejně jako "vzdálenému vlastníkovi" někdo ukrást) a na něm pracovat a zadávat/ukládat hesla, poskytl jsem tak údaje třetí osobě - vlastníkovi daného stroje? To stejné i u prohlížeče, pokud uložím heslo do správce hesel se zapnutou synchronizací, opět je heslo někde u někoho na serveru. Nebo ta nová chytrá schránka Win + V se zapnout synchronizací mezi zařízeními...

GMail tak jak ho chápu já je prostě standardní poštovní klient, který neběží lokálně, ale někde na serveru. Nevidím důvod, proč by měl být znevýhodňován na úkor ostatních klientů. Myslím, že je i v zájmu školy, aby studenti pokud možno ty emaily četly a potencionálním házením klacků pod nohy v podobě znevýhodňování troufnu si říct populárního klienta by tomu moc nepřispělo a to nehledě ještě na zmíněný certifikát, který v současné době znemožňuje použití zabezpečené komunikace.

Mimochodem, v textu se píše, že údaje nesmí uživatel poskytnout "jine osobě". Nic o třetí straně tam není, takže jiná osoba je i škola v tomto smyslu, pokud to dobře chápu. A jsme opět u smyslu této regulace, která takto jistě zamýšlena nebyla.

**Comment by ivskontrola** [comment]
@SuperMartas Nestačilo by maily přeposílat? Já jsem to tak dělal celé studium, nikdy jsem s tím neměl problém a jako workaround by to mohlo stačit. 

Případně by možná šel použít VUT Gmail účet...

**Comment by StoneboyCZ** [comment]
@SuperMartas Nestačilo by emaily přeposílat? Měl jsem to tak nastavené celé studim a fungovalo to celkem dobře. Import schránky to asi nenahradí, ale jako workaround by to mohlo stačit. 

Případně by možná šly použít GApps od VUT, ale ty jsem moc nezkoušel...

**Comment by ZdenekM** [comment]
> @SuperMartas Nestačilo by emaily přeposílat? Měl jsem to tak nastavené celé studim a fungovalo to celkem dobře. Import schránky to asi nenahradí, ale jako workaround by to mohlo stačit.

Přeposílání jde, ale nic moc to neřeší, když na ten přeposlaný e-mail potom člověk nemůže z GMailu odpovědět (nefunguje SMTP).

> Případně by možná šly použít GApps od VUT, ale ty jsem moc nezkoušel...

To je ale úplně jinej účet (aspoň teda u zamestnanců).

**Comment by SuperMartas** [comment]
Jo jo, možná jsem se špatně vyjádřil. Přeposílání samozřejmě jde a je úplně v pohodě, ale jde právě o tu odpověď, která bez SMTP bohužel nejde, pokud nepočítáme nečistou možnost posílání přes cizí SMTP servery, které jsou ale dle pravidel a na firewallu školy zakázány (viz https://www.fit.vut.cz/units/cvt/net/email.php.cs).

**Comment by Toaster192** [comment]
Je toto opraveno posledni zmenou s letsencrypt nebo pokryla zmena pouze cast problemu?

**Comment by kudlav** [comment]
Všechny výše uvedené servery používají Lets encrypt a SMTP server s Googlem dokáže komunikovat s SSL, takže vypadá, že je vše ok.
