### ISSUE TITLE
Obecne WIS Upgrady

### ISSUE THREAD

**Issue by Toaster192** [su-fit-vut/student-voice#40]
Prosim pridejte sve navrhy na zmeny ve WISu a s temi nejlepsimi pote pujdeme za Ing. Lampou

**Comment by davidbolvansky** [comment]
Upozornenie mailom na zverejneny posudok od veduceho/oponenta

**Comment by Toaster192** [comment]
Pridavam originalni request:
> prečo vo WIS je pod položkou Termíny zoznam predmetov a pod položkou Předměty menu na výber termínov. Už som si na to zvykol, ale vždy sa zamyslím nad tým, že prečo je to naopak.

**Comment by ilbinek** [comment]
> Pridavam originalni request:
> 
> > prečo vo WIS je pod položkou Termíny zoznam predmetov a pod položkou Předměty menu na výber termínov. Už som si na to zvykol, ale vždy sa zamyslím nad tým, že prečo je to naopak.

Ještě bych doporučil pouze prohodit pojmenování - nechat to na originálním místě, protože po nějaké době přeci jen všichni klikáme tam, kde to cca je.

**Comment by Atreides38** [comment]
Možnost v rozvrzích zobrazit pouze povinné předměty daného roku bez volitelných a také povinných předmětů z minulých let.

**Comment by deiwo** [comment]
Termíny skúšok v tabuľke termínov by mohli byť špeciálne zvýraznené, jednak tie, na ktoré sa dá prihlásiť a potom ešte inak tie, na ktoré je človek prihlásený. Hlavne preto, že teraz je to všetko zliate v jednej tabuľke, ktorá sa ani nedá sortovať. Fajn by bola možnosť si nastaviť farbu pre jednotlivé predmety.

**Comment by muzikovska** [comment]
Ve wisu by mohl přímo být odkaz na [přehled zkoušek](https://www.fit.vut.cz/study/advisor/20192020/zkouskyLS/max15/index.html).

**Comment by ondryaso** [comment]
Speciálně vyznačené termíny, do kterých se dá něco odevzdávat, ideálně různá podbarvení termínů, ve kterých už něco odevzdáno bylo, a těch, ve kterých ještě nic není.

**Comment by Toaster192** [comment]
> Ve wisu by mohl přímo být odkaz na přehled zkoušek.

Souhlasim akorat nebyl by lepsi [tenhle odkaz](https://www.fit.vut.cz/study/advisor/20192020/zkouskyLS/max15/1bitls.html)? (nevim jestli se k tomu da nejak pekne doklikat z toho co jsi poslal)

**Comment by StoneboyCZ** [comment]
> Ve wisu by mohl přímo být odkaz na [přehled zkoušek](https://www.fit.vut.cz/study/advisor/20192020/zkouskyLS/max15/index.html).

Tohle spíš vede na nějaký web generovaný přímo z WISu, Dobrý nápad, ale tuhle stránku bych primárně nepoužíval (vyučující totiž při jakékoli změně nebude měnit tohle ale když už, tak rozvrh ve WISu a pokud nám neřekne, že něco mění...

**Comment by muzikovska** [comment]
> > Ve wisu by mohl přímo být odkaz na přehled zkoušek.
> 
> Souhlasim akorat nebyl by lepsi [tenhle odkaz](https://www.fit.vut.cz/study/advisor/20192020/zkouskyLS/max15/1bitls.html)? (nevim jestli se k tomu da nejak pekne doklikat z toho co jsi poslal)

Na ten s tou tabulkou se doklikat dá z toho prvního (sekce **Tabulky pro jednotlivé ročníky**) a asi je to o preferenci, určitě by nevadilo, kdyby tam ty odkazy byly oba.



> > Ve wisu by mohl přímo být odkaz na [přehled zkoušek](https://www.fit.vut.cz/study/advisor/20192020/zkouskyLS/max15/index.html).
> 
> Tohle spíš vede na nějaký web generovaný přímo z WISu, Dobrý nápad, ale tuhle stránku bych primárně nepoužíval (vyučující totiž při jakékoli změně nebude měnit tohle ale když už, tak rozvrh ve WISu a pokud nám neřekne, že něco mění...

Ono by nebylo od věci ty termíny mít na jednom místě a z toho místa je tahat do všech tabulek, kde jsou zobrazené. Já mám zkušenost, že něktěří vyučující termín ve wisu zobrazí až na poslední chvíli, takže to stejně musím lovit vždycky tady. Nebo na kartě předmětu, ale tam to musím otvírat pro každý předmět zvlášť. Navíc netuším, jestli si vyučující mohou jen tak změnit nějaký termín, když se to plánuje centrálně.

**Comment by StupydHors** [comment]
Každý deadline by mohl mít studentem odškrtnutelnou kolonku "splněno".
Po přihlášení by se na pravé straně WISu mohla zobrazit tabulka nadcházejících termínu které ještě nejsou "splněny" ať už tedy registrace na semestrálku/cvičení nebo deadline projektu.

**Comment by isaranova** [comment]
Pokud dojde k nejake zmene v libovolnem terminu, tak by to melo zustat zvyraznene, dokud si student vylozene nerozklikne ten dany termin nebo neodklikne neco jako "vsechny zmeny v terminech precteny". Ted je to tak, ze pokud se udela treba 15 zmen v 40 ruznych terminech, tak po kliknuti na libovolny z nich vsechna ostatni upozorneni zmizi a uz nevim, kde mohlo dojit treba k uprave textu zadani, informaci ke zkousce, atd.

**Comment by Toaster192** [comment]
Mozna bych i zmenil to cislo u znamky (1A,2B,2C,3D,3E,4F) kdyz ve 2/6 pripadu je to napicu zaokrouhlene a nekolikrat jsem videl lidi se kvuli tomu zbytecne hadat (nebo byli obecne zmateni)

Bud cislo odstranit nebo tam proste pridat tech `.5`

**Comment by AntoninJarolim** [comment]
Chybi překlad "(pro nove studenty)" v anglické verzi.
![image](https://user-images.githubusercontent.com/60815963/87234432-18361480-c3d1-11ea-95cc-4cf041e39304.png)
![image](https://user-images.githubusercontent.com/60815963/87234436-22581300-c3d1-11ea-86fd-034dffdf9e36.png)

**Comment by ivory0juvo** [comment]
**Vyhledávač zapsaných/absolvovaných předmětů za celou dobu studia**

Bylo by zajímavé vytvořit stránku pro vyhledávání zapsaných či absolvovaných předmětů po celou dobu studia.

Příklad: 
Jsem magisterský student a potřebuji se dostat k učebním materiálům, které jsou k dispozici pouze na wiki stránce nějakého předmětu, který jsem měl v minulosti. Musím si rozkliknout přehled studia a tam v tabulce najít odkaz na předmět z toho roku. Poté se můžu dostat na wiki. V případě, že bych potřeboval bakalářský předmět, tak bych musel změnit studium na bakalářské a poté se tam "doklikat". 

Napadá mě několik možností:
a) Vyhledávač: student napíše klíčové slovo z názvu předmětu či jeho zkratku a zobrazí se předměty, obsahující takové klíčové slovo. Poté může snadno navštívit navštívit konkrétní předmět pro daný školní rok.

b) Rozcestník předmětů: stránka, která by obsahovala veškeré zapsané/absolvované předměty a přímo v rozcestníku by byly odkazy na wiki, kartu předmětu, privátní stránku, veřejnou stránku, externí stránku apod. V tomto rozcestníku by bylo zajímavé i zvýraznit ten odkaz, který garant předmětu upřednosňuje pro poskytování informací.

Vyhledávač by to samozřejmě nemusel být pouze pro tento případ užití, mohl by se generalizovat na obecný vyhledávač a postupně jej rozšiřovat (teoreticky veškeré odkazy, diskuzní fóra... to, co studenti často navštěvují).

**Comment by ivory0juvo** [comment]
**Další odkazy na studijní materiály**

Na stránkách jednotlivých předmětů jsou odkazy na kartu předmětu, soubory předmětu a Wiki. Některé předměty ale mají informace stále uložené na privátních stránkách či veřejných stránkách a některé předměty mají veškerou výuku úplně jinde. Bylo by dobré přidat i takové odkazy do této sekce.

**Comment by ivory0juvo** [comment]
**Zobrazení týdne**

Bylo by dobré na úvodní stránce zobrazit, kolikátý týden právě je, jaký je týden semestru a jestli je týden sudý nebo lichý.

**Comment by ivory0juvo** [comment]
**Odkazy na návody, FAQ a stránky stud. poradenství**

Přidat přímo do WISu odkazy na různé návody (např CVT či návody na registrace předmětů apod.), FAQ a na stránku stud. poradenství na jedno místo například do sekce Ostatní. Například jako stránku v Ostatní->Návody (či jiné pojmenování: FAQ, support...)

**Comment by StoneboyCZ** [comment]
> **Vyhledávač zapsaných/absolvovaných předmětů za celou dobu studia**
> 
> Bylo by zajímavé vytvořit stránku pro vyhledávání zapsaných či absolvovaných předmětů po celou dobu studia.
> 
> Příklad:
> Jsem magisterský student a potřebuji se dostat k učebním materiálům, které jsou k dispozici pouze na wiki stránce nějakého předmětu, který jsem měl v minulosti. Musím si rozkliknout přehled studia a tam v tabulce najít odkaz na předmět z toho roku. Poté se můžu dostat na wiki. V případě, že bych potřeboval bakalářský předmět, tak bych musel změnit studium na bakalářské a poté se tam "doklikat".
> 
> Napadá mě několik možností:
> a) Vyhledávač: student napíše klíčové slovo z názvu předmětu či jeho zkratku a zobrazí se předměty, obsahující takové klíčové slovo. Poté může snadno navštívit navštívit konkrétní předmět pro daný školní rok.
> 
> b) Rozcestník předmětů: stránka, která by obsahovala veškeré zapsané/absolvované předměty a přímo v rozcestníku by byly odkazy na wiki, kartu předmětu, privátní stránku, veřejnou stránku, externí stránku apod. V tomto rozcestníku by bylo zajímavé i zvýraznit ten odkaz, který garant předmětu upřednosňuje pro poskytování informací.
> 
> Vyhledávač by to samozřejmě nemusel být pouze pro tento případ užití, mohl by se generalizovat na obecný vyhledávač a postupně jej rozšiřovat (teoreticky veškeré odkazy, diskuzní fóra... to, co studenti často navštěvují).

Nestačila by stránka s přehledem předmětů ve všech studiích? Něco takového už v (učitelském) WISu je, tak by to nemuselo být složité na doimplementaci.

**Comment by StoneboyCZ** [comment]
> **Další odkazy na studijní materiály**
> 
> Na stránkách jednotlivých předmětů jsou odkazy na kartu předmětu, soubory předmětu a Wiki. Některé předměty ale mají informace stále uložené na privátních stránkách či veřejných stránkách a některé předměty mají veškerou výuku úplně jinde. Bylo by dobré přidat i takové odkazy do této sekce.

Jiné odkazy jsou na kartě předmětu a pokud nejsou, je to chyba někde v organizaci předmětu. Přímo do WISu asi přidat nepůjdou (ale učitel je může vložit do aktuálních informací a odkaz je vidět u termínů).

**Comment by StoneboyCZ** [comment]
> **Zobrazení týdne**
> 
> Bylo by dobré na úvodní stránce zobrazit, kolikátý týden právě je, jaký je týden semestru a jestli je týden sudý nebo lichý.

Je to u rozvrhu, takže asi nebude problém doplnit i do WISu :).

**Comment by kudlav** [comment]
Možnost vyplňovat a ukládat (jako koncept) hodnocení předmětu průběžně po celý rok, na konci roku po _otevření dotazníků_ jen odeslat.

**Comment by kudlav** [comment]
> 
> 
> > **Zobrazení týdne**
> > Bylo by dobré na úvodní stránce zobrazit, kolikátý týden právě je, jaký je týden semestru a jestli je týden sudý nebo lichý.
> 
> Je to u rozvrhu, takže asi nebude problém doplnit i do WISu :).

Ale u osobního rozvrhu aktuální týden rovněž chybí.

**Comment by StoneboyCZ** [comment]
> > > **Zobrazení týdne**
> > > Bylo by dobré na úvodní stránce zobrazit, kolikátý týden právě je, jaký je týden semestru a jestli je týden sudý nebo lichý.
> > 
> > 
> > Je to u rozvrhu, takže asi nebude problém doplnit i do WISu :).
> 
> Ale u osobního rozvrhu aktuální týden rovněž chybí.

Myšleno jako třeba tady: https://www.fit.vut.cz/study/schedule/229/

**Comment by StoneboyCZ** [comment]
Jinak obecně k issue: ing. Lampa je dlouhodobě nemocný, takže aktuálně bych s žádnými upgrady nepočítal :(.

**Comment by cernyd** [comment]
Posledních několik dní jsem se potýkal s kuriózní chybou - snažil jsem se přihlásit do WISu ale záhadně to s mým uloženým loginem nefungovalo, nakonec se ukázalo že se před můj login name uložila v prohlížeči mezera.

Nebylo by možné při autorizaci uživatele odstranit mezery před a za loginem uživatele nebo aspoň ukázat nějaké varování?

**Comment by cernyd** [comment]
Posledních několik dní jsem se potýkal s kuriózní chybou - snažil jsem se přihlásit do WISu ale záhadně to s mým uloženým loginem nefungovalo, nakonec se ukázalo že se před můj login name uložila v prohlížeči mezera.

Nebylo by možné při autorizaci uživatele odstranit mezery před a za loginem uživatele nebo aspoň ukázat nějaké varování?

**Comment by kudlav** [comment]
Formuláře podporující HTML mažou některé tagy (např. img, code). Rovněž některé znaky mění za jiné (např. české uvozovky). Bylo by vhodné k formuláři doplnit seznam povolených tagů a znaků. Nebo alespoň možnost zobrazit náhled před odesláním. Nebo alespoň zobrazit varování před zásahem do textu. Idelálně ale nechat zprávu tak, jak ji uživatel napsal.

Lampa v odpovědi pouze konstatoval, že tomu skutečně tak je ale zjevně s tím nic dělat nehodlá.

**Comment by Toaster192** [comment]
WIS upgrady uz asi nebudou relevantni :cry: uzavirame
