### ISSUE TITLE
Záznamy, streaming a korona

### ISSUE THREAD

**Issue by Honza0297** [su-fit-vut/student-voice#41]
Nešlo by znovu zatlačit na vedení fakulty (ideálně ještě před semestrem), aby se co nejvíc přednášek, kde je to možné, začalo streamovat a/nebo zaznamenávat? 

VUT dneska vydalo nové pokyny, kde je mj. napsané, že do prostorů VUT mají zakázaný vstup lidé s příznaky infekčního onemocnění - a upřímně, v zimě kašle nebo posmrkává fakt hodně lidí, takže by účast na přednáškách dělala spoustě lidí problémy. 

Nemluvě o tom, že věčný argument o "zaplnění přednáškovek" je v tomhle období taky kaput - v současné chvíli by se všichni měli snažit o pravý opak - čím míň lidí, tím líp.

**Comment by StoneboyCZ** [comment]
V zápisu z KD bude/bylo:
Doporučujeme vyučujícím v zimním semestru 2020/2021, aby povolili pořizování záznamů ze svých přednášek a zpřístupňovali je min. studentům s překážkou ve studiu (zejména onemocnění Covid-19 nebo karanténní či související opatření) a srdečně děkujeme těm, co se již rozhodli záznamy pořizovat. Respektujeme však rozhodnutí těch, kteří chtějí chránit svá osobnostní práva a záznamy nepřipraví. 

Nic víc pokud vím vedení aktuálně dělat nebude. Ze zákona není možné nikoho do pořizování záznamů nutit a tato výzva je maximum, co se podařilo prosadit.

**Comment by Honza0297** [comment]
@StoneboyCZ  Díky za info! 

Rozhodně jsem nemyslel, aby se vyučujícím začalo vyhrožovat nějakou povinností ze zákona, jen chci tohle téma udržet co nejživější, jelikož záznamy jsou něco, co by mnoha lidem fakt pomohlo. Nejen kvůli tomu, že věci z přednášek se ne vždycky dají pochopit na první dobrou, ale také kvůli tomu, že pak někteří chodí do školy s rýmou, kašlem nebo regulérně nemocní jen proto, že přednáška není zaznamenávaná a učební materiály jsou ne vždycky použitelné. A určitě jsem nevyčerpal zdaleka všechny důvody.

**Comment by Toaster192** [comment]
> Rozhodně jsem nemyslel, aby se vyučujícím začalo vyhrožovat nějakou povinností ze zákona

Obavam se ze na velkou cast vyucujicich to jinak nepujde :cry:

**Comment by StoneboyCZ** [comment]
@Toaster192 Ale někteří vyučující, kteří záznamy nikdy nechtěli, mají teď trochu jiný názor vzhledem ke koroně. Uvidíme.

**Comment by Honza0297** [comment]
> > Rozhodně jsem nemyslel, aby se vyučujícím začalo vyhrožovat nějakou povinností ze zákona
> 
> Obavam se ze na velkou cast vyucujicich to jinak nepujde cry

Fakt doufám, že nemáš pravdu :smile:. Chce to prostě pořád udržovat debatu a ukazovat, že my - studenti - ty záznamy skutečně hodně chceme a časem se prostě něco změnit musí! Je ale docela smutné, že vyučující na informatické fakultě odmítají moderní řešení, zvlášť, když HW a infrastruktura jsou na záznamy připravené a počítalo se s nimi. 

Mimochodem, ze stran těch vyučujících jde o nějakou věcnou argumentaci, nebo je to ve stylu "záznamy dělat nebudu, protože je dělat nebudu"?

**Comment by StoneboyCZ** [comment]
@Honza0297 @Toaster192 Ta argumentace je jednoduchá: pokud jsou záznamy, klesá návštěvnost přednášek. A je snaha, aby studenti navštěvovali pokud možno všechny přednášky a ne se jen dívali na jejich záznamy tři dny před zkouškou.

**Comment by Darkvikis** [comment]
@Honza0297 Musíme akceptovat i argumenty "Nechci dělat záznamy, protože nechci aby byl můj záznam na netu." . Ti vyučující se tak brání nějakému parodování apod.

**Comment by StoneboyCZ** [comment]
@Honza0297 @Darkvikis A ano, i tohle je relevantní argument.

**Comment by StoneboyCZ** [comment]
> @Honza0297 Musíme akceptovat i argumenty "Nechci dělat záznamy, protože nechci aby byl můj záznam na netu." . Ti vyučující se tak brání nějakému parodování apod.
Ano, i tohle je relevantní argument.

**Comment by Honza0297** [comment]
> @Honza0297 @Toaster192 Ta argumentace je jednoduchá: pokud jsou záznamy, klesá návštěvnost přednášek. A je snaha, aby studenti navštěvovali pokud možno všechny přednášky a ne se jen dívali na jejich záznamy tři dny před zkouškou.

To jsem si bohužel myslel. 

Je mi jasné, že nejsem ani zdaleka první ani poslední, kdo to napíše, ale takoví vyučující by měli v první řadě zjistit, **proč** jim na přednášky chodí málo lidí a v ideálním případě to změnit tak, aby přednášky byly pro studenty hodnotnější. Schválně nepíšu "záživnější" nebo "zábavnější", cílem je něco se naučit, to je jasné, ale i to jde pojmout tak, že to člověka baví (nebo to aspoň není vyložená nuda), příkladů máme i na FIT hromadu. A na přednáškách, kde se tohle daří, je návštěvnost vysoká, i přes veřejné záznamy. 

Zákaz záznamů je možná jednoduchý a funkční, ale v určitém směru i nelogický - cca v polovině předmětů (často těch bez záznamů) nám přednášející říkali "slajdy jsou pro mě, choďte na přednášky". OK, chodil jsem, ale na první dobrou toho tolik pobrat nejde (zvlášť, když má člověk několik přednášek v kuse). A kde pak mám hledat informace? Slajdy jsou jen osnova pro přednášejícího, výpisky sice mít můžu, ale pokud jsem to na přednášce nepochopil, tak jsem si to pravděpodobně ani nezapsal, na hlední informace v referenční literatuře není během semestru čas... Neříkám, že to nejde, ale v konečném důsledku toho vím míň, než kdybych ty záznamy měl a mohl si všechno ujasnit.

**Comment by Honza0297** [comment]
> @Honza0297 Musíme akceptovat i argumenty "Nechci dělat záznamy, protože nechci aby byl můj záznam na netu." . Ti vyučující se tak brání nějakému parodování apod.

> @Honza0297 @Darkvikis A ano, i tohle je relevantní argument.

Určitě to je relevantní argument, na druhou stranu, pokud si někdo ze studentů bude chtít udělat legraci z přednášejícího, nějaký materiál pro parodování si najde vždycky. A aby kvůli tomu "trpěli" i všichni ostatní, kteří chtějí využít přednášky jen na studium, je dost nešťastné. 

Nemluvě o tom, že určitě forma parodování vyučujících tu byla snad vždycky a pokud to skutečně jsou jen drobné parodie a ne vyloženě šikana daného vyučujícího (netuším, jestli ti vyučující s tím už měli zkušenosti, nebo záznamy zakázali preventivně), je otázkou, jestli je nutné kvůli tomu ty záznamy zakazovat. Ale znovu říkám, záleží na okolnostech.

**Comment by Honza0297** [comment]
Tohle se už vyřešilo samo, takže s klidem zavírám.
