### ISSUE TITLE
WIS login neodstraňuje whitespace kolem loginu

### ISSUE THREAD

**Issue by cernyd** [su-fit-vut/student-voice#42]
Posledních několik dní jsem se potýkal s kuriózní chybou - snažil jsem se přihlásit do WISu ale záhadně to s mým uloženým loginem nefungovalo, nakonec se ukázalo že se před můj login name uložila v prohlížeči mezera.

Nebylo by možné při autorizaci uživatele odstranit mezery před a za loginem uživatele nebo aspoň ukázat nějaké varování?

**Comment by Toaster192** [comment]
Muzu mozna poprosit o repost do #40 ? Ale mozna si tohle zaslouzi vlastni issue

Jinak pripominam ze Ing. Lampa je momentalne nedostupny takze veskere zmeny s WISem jsou alespon v nejblizssi dobe docela nepravdepodobne :(

**Comment by cernyd** [comment]
@Toaster192 ok closenu toto a repostnu.
