### ISSUE TITLE
IOS půlsemka v pátek odpoledne

### ISSUE THREAD

**Issue by JustJarda** [su-fit-vut/student-voice#45]
Kdo dává půlsemku v pátek odpoledne :jardaCantBelieveThisShit:

**Comment by jackorp** [comment]
Co tepr v pátek v 6 večer :smrckaSeemsGood:

**Comment by StoneboyCZ** [comment]
Nikdy jindy není bezkolizně volno pro všechny.

**Comment by lukynmatuska** [comment]
Please close this Issue. IOS polsemka už bola.

**Comment by michkot** [comment]
Past event
