### ISSUE TITLE
Špatné pokrytí Wi-Fi signálu v A208

### ISSUE THREAD

**Issue by lukynmatuska** [su-fit-vut/student-voice#46]
Pod [rampou v budově A](https://www.fit.vut.cz/fit/room/A208) je velice slabý signál.

Podle mapy je nejbližší AP v [A302](https://www.fit.vut.cz/fit/room/A302) a další je až v místnosti [A212](https://www.fit.vut.cz/fit/room/A212).

Velmi pravděpodobně signál neprochází přes kovovou konstrukci a několik zdí, tak jak někdo očekával.

**Comment by StoneboyCZ** [comment]
O špatné kvalitě Wifi v budově A víme a dlouhodobě se řeší. Je to možná na dotaz na KD.

**Comment by KuchynkaMarek** [comment]
Včera byl v [A208](https://www.fit.vut.cz/fit/room/A208/) Ing. Čejkou zprovozněn (díky Vašemu podnětu) nový AP. Pokud by se našlo ještě nějaké takové místo, určitě napište. V AP teď probíhá menší reorganizace, takže je správný čas to řešit.

**Comment by lukynmatuska** [comment]
Děkuji.
