### ISSUE TITLE
Mikrovlnka P108

### ISSUE THREAD

**Issue by DanValnicek** [su-fit-vut/student-voice#48]
Bylo by možné přidat mikrovlnku do P108? Nejbližší mikrovlnka ke které máme přístup je až v bloku A.

**Comment by ondryaso** [comment]
Zdravím, ano, už je objednaná mikrovlnka i rychlovarná konvice, do konce roku se tam objeví.

**Comment by ondryaso** [comment]
A čirou náhodou to přišlo zrovna dneska, takže už jsem je tam umístil. Zavírám issue.
