### ISSUE TITLE
Místnosti pro studenty k rezervaci

### ISSUE THREAD

**Issue by Redak37** [su-fit-vut/student-voice#5]
Nešlo by nějak zařídit více místností pro studenty k rezervaci? Ty 4, které jsou, jsou často bohužel nedostatečné. (V době, kdy se řeší týmové projekty jsou neustále všechny obsazené.)

**Comment by ivory0juvo** [comment]
Řeší se možnost rezervovat "temnou místnost" v zámečku, ke studiu lze navíc využít:
- místnosti v CVT, nejsou-li obsazeny,
- chodby, kde jsou umístěny tabule:
![map](https://user-images.githubusercontent.com/6269650/53801059-78e05200-3f3e-11e9-9c3a-5c4631e792a3.png)

**Comment by Jeffi2** [comment]
Do nově zpřístupněné místnosti G104 by to chtělo přivést wifi. Přípojky tam na to jsou, případně hned za stěnou do knihovny jsou na zdi další.

**Comment by ivory0juvo** [comment]
Wifi (eduroam) jsme tam testovali asi 2 týdny zpátky (2 notebooky a jeden mobil), vše fungovalo. 

Řešili jsme, že v knihovně, jak je ten stůl a tabule, wifi nefungovala minulý semestr a požádali jsme CVT o zesílení pokrytí (právě i kvůli vznikající studovně).

Můžu poprosit o případný popis problému?

**Comment by Jeffi2** [comment]
Byli jsme tam pár dní po tom, co jste tu místnost otevřeli a žádný signál tam nebyl. Pokud už je to vyřešeno, tak super.

**Comment by TheKuko** [comment]
> ke studiu lze navíc využít:
> 
> * místnosti v CVT, nejsou-li obsazeny,

To som cital, ale ked som sa pytal vratnicky ohladom pristupu do niektorej ucebne z M/N/O (uz neviem, ktora to bola), pretoze tam momentalne nebola vyuka, ale neskor som tam mal mat cviko a nechcelo sa mi prechadzat medzi ucebnami - chcel som si sadnut tam, robit si svoje a pockat do vyuky (mozno >=1h uz neviem), tak mi povedala, ze v ziadnom pripade....ze na to mame vyhradene priestory dolu a ucebne su len na vyuku.

**Comment by StoneboyCZ** [comment]
@TheKuko Dobrý den, dnes jsem se na to ptal na KD. V podstatě jde o to, že učebny, které nejsou běžně dostupné pro volné využití se mohou volně využít pouze v případě, že jsou všechny učebny pro volné využití obsazeny.

**Comment by Jeffi2** [comment]
@ivory0juvo Jak dopadlo znovu ověření funkčnosti WiFi? Minulý týden jsem byl s týmem v G104 a nikdo z nás nebyl schopný se tam připojit.

**Comment by Toaster192** [comment]
Pokud si dobře pamatuji tak problém byl zadán do wisu (pod učitelským účtem) jako závada, takže by o problému měli vědět správní lidé a snad jej brzy vyřešit.

**Comment by Jeffi2** [comment]
@Toaster192 Tzn., že to ve Wisu leží měsíc bez odezvy? Kdo jsou "správní lidé", kteří to mají na starost? Pro jistotu přestala WiFi fungovat i v C211.

**Comment by Toaster192** [comment]
Předpokládám že toto má na starost Ing. Petr Lampa, poptám se o přidání C211 :)

**Comment by Budovi** [comment]
V riešení je ako G104 tak aj C211, nie je to bez odozvy, a ak všetko pôjde podľa plánu, nápravy by sme sa mali dočkať v najbližších dňoch.

**Comment by Budovi** [comment]
Včera došlo k doplneniu AP v G108. Bol som aj v C211 a pokrytie tam síce je, ale nemal som príležitosť dlhšie testovať.

Každopádne prosím o otvorenie nového issue v prípade, že to bude neuspokojivé. Toto issue by som uzavrel, nemá zmysel ho ďalej živiť v prípade, že sa nebude jednať o nové priestory / rezervácie (už tá wifi je tak napol off topic) @Toaster192 .

**Comment by Toaster192** [comment]
Souhlasim 👍
