### ISSUE TITLE
Vylepšeni deskovek

### ISSUE THREAD

**Issue by Bordovsky** [su-fit-vut/student-voice#6]
**Zvyšení atraktivity deskovek**

Posledni dobou je na deskovkách meně a meně lidi. Naposledy (25.2.2019) byli jen čtyři. Mam pocit že se navic schazeji pořad ti sami lide. Planuje se lidi nějak vice motivovat? Napřiklad nějake lakavějši ceny, než mala deskovka/karetka pro par lidi? Připadně dělat turnaj v nějake težši ale lakavější hře? Přeci jen Duchove v koupelně nepusobi jako intelektualně vyzivava hra na to aby přitahla spoustu vysokoškoláků.  Chapu že je potřeba hry s relativně krátkou dobou na hru. Znam turnaje v hrach jako jsou Osadnici z katanu, Dixit, Mars Teramorface, ale pokud by po zapisu byla hodinka na pravidla/cvik myslim že by to šlo. Taky myslim že i ceny, napřiklad poukazky do čajovny nebo někam by mohly lidi trochu vic lakat.

**Comment by kam29** [comment]
Děkuji za komentář.
Malá účast na posledních deskovkách byla dle mého názoru způsobena tím, že nebyl otevřený bar a ani Kachna pro veřejnost. Hodně lidí přijde do Kachny jen tak a když zjistí, že je turnaj, tak se přidají.
Na deskovkových turnajích v minulém semestru byl účastníků hodně a dokonce myslím, že i více než v minulých letech.
Co se týká lákavějších cen, na tímto už jsme uvažovali a plánujeme být v příštím školním roce trochu kreativnější a investovat do toho více peněz pokud to bude možné. 
A poslední věc ohledně komplikovanějších her: Prozatím jsme se drželi her menších a jednodušších, právě z časových důvodů. Dalším důvodem je, že (z mé zkušenosti) většina účastníků nezná pravidla hry na začátku turnaje. Pokud o to budu vidět větší zájem, zvážím i turnaj v nějaké komplikovanější hře. Například Osadníci z Katanu je myslím dobrý kompromis. Dixit se bohužel v turnajích hrát nedá, protože silně spoléhá na to, či se hráči znají/neznají. Mars Teraformace je bohužel časově nerealizovatelné.

**Comment by Toaster192** [comment]
Jelikož se jedná o nejdéle nekomentovaný příspěvek, který se již vyřešil / může vyřešit v soukromé konverzaci, uzavírám issue.
