### ISSUE TITLE
Platba kartou v automatech v E

### ISSUE THREAD

**Issue by michkot** [su-fit-vut/student-voice#8]
Bylo by hezké, kdyby šlo v automatech na kafe a nápoje/jídlo v E platit kartou, ne vždycky máme u sebe potřebnou částku v mincích.

**Comment by ivory0juvo** [comment]
Realizováno teď v únoru, 2019

**Comment by risinek** [comment]
Funguje to super na těch automatech, používám to od první chvíle. Sice to trvá, bez naváže spojení, ale stokrát lepší, než žádná možnost platby kartou.
